"""Configuration management for GitHub Standup Agent."""

import os
from pathlib import Path

from pydantic import Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

# Config directory
CONFIG_DIR = Path.home() / ".config" / "standup-agent"
CONFIG_FILE = CONFIG_DIR / "config.json"
DB_FILE = CONFIG_DIR / "standup_history.db"
STYLE_FILE = CONFIG_DIR / "style.md"
SESSIONS_DB_FILE = CONFIG_DIR / "chat_sessions.db"


class StandupConfig(BaseSettings):
    """Configuration for the standup agent."""

    model_config = SettingsConfigDict(
        env_prefix="STANDUP_",
        env_file=".env",
        extra="ignore",
    )

    # API Key (required)
    openai_api_key: SecretStr | None = Field(
        default=None,
        validation_alias="OPENAI_API_KEY",
    )

    # GitHub settings
    github_username: str | None = None  # Auto-detected from `gh auth status` if not set

    # Agent settings
    default_days_back: int = 1
    default_output: str = "stdout"  # stdout, clipboard
    coordinator_model: str = "gpt-4o"
    data_gatherer_model: str = "gpt-4o-mini"
    summarizer_model: str = "gpt-4o"
    temperature: float = 0.7

    # Repos to include/exclude (empty = all)
    include_repos: list[str] = Field(default_factory=list)
    exclude_repos: list[str] = Field(default_factory=list)

    # History settings
    history_days_to_keep: int = 30

    # Style customization (short instructions, use style.md file for detailed customization)
    style_instructions: str | None = None

    def save(self) -> None:
        """Save configuration to file."""
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        # Don't save the API key to file for security
        CONFIG_FILE.write_text(self.model_dump_json(indent=2, exclude={"openai_api_key"}))

    @classmethod
    def load(cls) -> "StandupConfig":
        """Load configuration from file and environment."""
        if CONFIG_FILE.exists():
            file_config = CONFIG_FILE.read_text()
            return cls.model_validate_json(file_config)
        return cls()

    def get_api_key(self) -> str:
        """Get the OpenAI API key, raising an error if not set."""
        if self.openai_api_key is None:
            # Check environment directly as fallback
            env_key = os.getenv("OPENAI_API_KEY")
            if env_key:
                return env_key
            raise ValueError(
                "OpenAI API key not found. Set OPENAI_API_KEY environment variable "
                "or use `standup config --set-openai-key`"
            )
        return self.openai_api_key.get_secret_value()


def get_github_username() -> str | None:
    """Get the GitHub username from gh CLI."""
    import subprocess

    try:
        result = subprocess.run(
            ["gh", "api", "user", "--jq", ".login"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def load_style_from_file() -> str | None:
    """Load custom style instructions from style.md file."""
    if STYLE_FILE.exists():
        content = STYLE_FILE.read_text().strip()
        if content:
            return content
    return None


def get_combined_style_instructions(config: StandupConfig) -> str | None:
    """
    Get combined style instructions from config and style file.

    Priority: style.md file content + config.style_instructions
    Both are combined if present.
    """
    parts = []

    # Load from file first (primary source for detailed instructions)
    file_style = load_style_from_file()
    if file_style:
        parts.append(file_style)

    # Add config style instructions (good for quick overrides)
    if config.style_instructions:
        parts.append(config.style_instructions)

    if parts:
        return "\n\n".join(parts)
    return None


def create_default_style_file() -> Path:
    """Create a default style.md file with example content."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    default_content = """# Standup Style Customization

Customize how your standup summaries are generated by editing this file.
The instructions here will be passed to the AI summarizer.

## Example Instructions (uncomment and modify as needed):

# - Keep summaries very concise (3-5 bullet points max)
# - Use emoji for status: ✅ merged, 🔄 in progress, 🚧 blocked
# - Group items by project/repo instead of activity type
# - Skip the blockers section unless there's something critical
# - Focus on outcomes and impact, not just what was done
# - Include PR/issue numbers as links
# - Use past tense for completed work, present for ongoing

## Your Custom Instructions:

"""
    STYLE_FILE.write_text(default_content)
    return STYLE_FILE
